name: gymbro
description: I Got You.
publish_to: 'none'
version: 0.6.9

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.2
  flutter_spinkit: ^5.2.0
  google_fonts: ^4.0.5
  provider: ^6.0.5
  get: ^4.6.5
  intl: ^0.17.0
  toggle_switch: ^2.1.0
  gender_picker: ^1.1.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  shared_preferences: ^2.1.1
  charts_flutter: ^0.12.0
  file_picker: ^4.2.0
  open_file: ^3.2.1
  fl_chart: ^0.36.2
  line_icons: ^2.0.0
  calendar_date_picker2: ^0.5.2
  flutter_svg: ^2.0.6
  flutter_facebook_auth: ^4.4.1+1
  google_sign_in: ^5.4.4
  image_picker: ^0.8.7+5
  dotted_border: ^2.0.0+3
  sqflite: ^2.2.8+4
  animated_bottom_navigation_bar: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcon/android/play_store_512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/appIcon/web/apple-touch-icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/appIcon/web/apple-touch-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/appIcon/ios/AppIcon-40@3x.png" 
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/pics/
    - assets/
    - assets/fonts/
    - assets/Gym/
    - assets/appIcon/android/
    - assets/ahmed.png