// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS0XEWxDuCMRtTFVozRDQNgbaflK2Skq0',
    appId: '1:987559794584:web:a79b92fa9b41f5dc397ded',
    messagingSenderId: '987559794584',
    projectId: 'gymbro-81509',
    authDomain: 'gymbro-81509.firebaseapp.com',
    storageBucket: 'gymbro-81509.appspot.com',
    measurementId: 'G-XWB8WX4FYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiPKw7cttxy8O_JXgJ_xY1fi5uWUYAgVo',
    appId: '1:987559794584:android:6ea0042b9689d59f397ded',
    messagingSenderId: '987559794584',
    projectId: 'gymbro-81509',
    storageBucket: 'gymbro-81509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQPiy1_cN3WZLLPvHfUeF1E_YmMXrq3Dk',
    appId: '1:987559794584:ios:83662085813e1258397ded',
    messagingSenderId: '987559794584',
    projectId: 'gymbro-81509',
    storageBucket: 'gymbro-81509.appspot.com',
    androidClientId: '987559794584-jah8kfdpecus8m3anekhct3o3bpod1q6.apps.googleusercontent.com',
    iosClientId: '987559794584-b0rpmheehcfqo8scjbgiks0hhr8t5o3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymbro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQPiy1_cN3WZLLPvHfUeF1E_YmMXrq3Dk',
    appId: '1:987559794584:ios:d23d95a0d605d2a0397ded',
    messagingSenderId: '987559794584',
    projectId: 'gymbro-81509',
    storageBucket: 'gymbro-81509.appspot.com',
    androidClientId: '987559794584-jah8kfdpecus8m3anekhct3o3bpod1q6.apps.googleusercontent.com',
    iosClientId: '987559794584-hg7jephjp04pmj2n120vkp3vplquci3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymbro.RunnerTests',
  );
}
